In [29]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np 
from numpy import linalg
import scipy 

In [30]:
U = np.array([[-5, 2, 0, -2, -3],
              [0, 1, 0, -5, 4],
              [0, 0, 1,-1, 1],
              [0, 0, 0, 4, -2],
              [0, 0, 0, 0, 4]], int)

L = np.array([[1,0,0,0,0],
              [3,1,0,0,0],
              [0,2,1,0,0],
              [2,2,-4,1,0],
              [5,-4,-3,-2,1]], int)

b = np.array([2,-3,-3,2,3], int)

A=np.dot(L,U)

n=5

In [31]:
print(A)
Ainv = linalg.inv(A) #inverse element 
print(Ainv)

[[ -5   2   0  -2  -3]
 [-15   7   0 -11  -5]
 [  0   2   1 -11   9]
 [-10   6  -4  -6  -4]
 [-25   6  -3   5 -26]]
[[-1.01500000e+01  4.10000000e+00 -2.25000000e+00 -3.00000000e-01
  -3.50000000e-01]
 [ 1.06250000e+01 -3.25000000e+00  8.75000000e-01  5.00000000e-01
  -3.75000000e-01]
 [ 5.87500000e+00 -1.75000000e+00  6.25000000e-01 -2.99760217e-16
  -1.25000000e-01]
 [ 1.41250000e+01 -5.25000000e+00  2.37500000e+00  5.00000000e-01
   1.25000000e-01]
 [ 1.42500000e+01 -5.50000000e+00  2.75000000e+00  5.00000000e-01
   2.50000000e-01]]


In [7]:
x = linalg.solve(A,b).reshape(n) #how does this even work?
print(x)

[-27.5   28.25  14.75  38.25  38.5 ]


In [26]:
from numpy import zeros, array, dot, empty 
#Gaussian elimination
U = array([[-5,2,0,-2,-3],
           [0,1,0,-5,4],
           [0,0,1,-1,1],
           [0,0,0,4,-2],
           [0,0,0,0,4]],float)

L = array([[1,0,0,0,0],
          [3,1,0,0,0],
          [0,2,1,0,0],
          [2,2,-4,1,0],
          [5,-4,-3,-2,1]],float)
b= array([2,-3,-3,2,3],float)
N = len(b)
A =dot(L,U) 

for m in range(N):
   
    #Divide by the diagonal element 
    div = A[m,m]
    A[m,:] /= div # rows elements  
    b[m]/= div 
    #Now subtract from the lower rows
    for i in range(m+1, N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        b[i] -= mult*b[m]
        print
x = empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = b[m]
    for i in range(m+1, N):
        x[m] -= A[m,i]*x[i]
        
print(x) 
        


[-27.5   28.25  14.75  38.25  38.5 ]


In [81]:
U = array([[-5,2,0,-2,-3],
           [0,1,0,-5,4],
           [0,0,1,-1,1],
           [0,0,0,4,-2],
           [0,0,0,0,4]],float)

L = array([[1,0,0,0,0],
           [3,1,0,0,0],
           [0,2,1,0,0],
           [2,2,-4,1,0],
           [5,-4,-3,-2,1]],float)
A=dot(L,U)

I = array([[1,0,0,0,0],
           [0,1,0,0,0],
           [0,0,1,0,0],
           [0,0,0,1,0],
           [0,0,0,0,1]],float)
# gaussian elimation  
for m in range(N):
    
    div = A[m,m]  
    A[m,:]/= div  
    A[:,m]/= div
    
# Now subtract from the lower rows
    for i in range(m+1, N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        b[i] -= mult*b[m]
x = empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = b[m]
    for i in range(m+1, N):
        x[m] -= A[m,i]*x[i]
 
 
        
print(A)

[[ -0.2         -0.04878049  -0.           0.4          0.6       ]
 [  0.43902439   0.12195122   0.          -1.48780488  -0.82926829]
 [ -0.10707912   0.21415824   1.         -10.63712076   9.20226056]
 [  2.           0.73170732  -4.          -6.          -4.        ]
 [  5.           0.73170732  -3.           5.         -26.        ]]


In [87]:
#test sample 

from numpy import array 
A = array([[1,2,3],
           [2,3,1],
           [3,2,1]],float)
N = len(A)
for m in range(N):
    
    A = array([[1,2,3],
               [2,3,1],
               [3,2,1]],float)
    I = array([[1,0,0],
               [0,1,0],
               [0,0,1]],float)

    print(A[0,:]) 

    

[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [88]:
for m in range(N):
   
    #Divide by the diagonal element 
    div = A[m,m]
    A[m,:] /= div # rows elements  
    b[m]/= div 
    #Now subtract from the lower rows
    for i in range(m+1, N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        b[i] -= mult*b[m]
        print(mult)

2.0
3.0
-4.0
